### ISSUE TITLE
Recommend compile using `:static-fns true`

### ISSUE THREAD

**Issue by mfikes** [theasp/cljs-webrepl#2]
Otherwise if you do `(ns foo.core)` and then `(defn f [x] (* x x))` the first `defn` will be slow if in Safari.

See

https://www.youtube.com/watch?v=AMT63rxK4E8

**Comment by theasp** [comment]
Interesting.  The docs seem to imply that you won't be able to redefine functions with that option, but it appears to work.

https://github.com/clojure/clojurescript/wiki/Compiler-Options#static-fns

**Comment by theasp** [comment]
It should be building with this on as we speak.  Thanks!

**Comment by mfikes** [comment]
Hi @theasp You can compile the source for `cljs-webrepl` itself with `:static-fns true`. (No need to actually use it for evaluated expressions to avoid the perf issue associated with the first `defn`.)
